spring:
  datasource:
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:tcp://localhost/~/datajpa
#    username: sa
#    password:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5432/testdb
      hikari:
        username: postgres
        password: postgres
        connection-test-query: 'select 1'

  jpa:
    hibernate:
      ddl-auto: create # ? ??? ?????? ?? ??? ???? drop ??, ?? ????.
    properties:
      hibernate:
#        show_sql: true # System.out ? ?????? ?? SQL? ???.
        format_sql: true

#gloable 설정

  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 2000
        # index parameter start 1 ( default 0 ) Pagable , Page의 값이 다름,,
        one-indexed-parameters: true


logging:
  level:
    org.hibernate.sql: debug # ??? logger? ?? ?????? ?? SQL? ???.
#    org.hibernate.type: trace
server:
  port: 48080

management:
  endpoints:
    web:
      exposure:
        include: prometheus
  endpoint:
    prometheus:
      enabled: true